---
server:
  contextPath: '/thikthak'
  port: 7575
  session:
    timeout: 3600  #seconds
grails:
    profile: web
    codegen:
        defaultPackage: wtsapi
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: werp
#    password: 'werp#'
    driverClassName: oracle.jdbc.OracleDriver
    username: 'THIKTHAK'
    password: 'THIK'

environments:
    development:
        dataSource:
            dbCreate: update #create-drop, update
#            url: jdbc:mysql://localhost/wtsapp?serverTimezone=UTC
#            url: 'jdbc:oracle:thin:@192.168.200.64:1521:hrpos'
            url: 'jdbc:oracle:thin:@192.168.1.70:1521:DITF'
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update #create-drop, update
#            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#            url: 'jdbc:oracle:thin:@192.168.200.64:1521:hrpos'
            url: 'jdbc:oracle:thin:@192.168.1.70:1521:DITF'
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 1800000
                minEvictableIdleTimeMillis: 1800000
#                validationQuery: SELECT 1
                validationQuery: SELECT 1 FROM DUAL
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

plugin:
        springsecurity:
            controllerAnnotations:
                chainMap:
                    '/api/**': 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter'
                    '/**': 'JOINED_FILTERS,-restTokenValidationFilter,-restExceptionTranslationFilter'
            rest:
                logout:
                    endpointUrl: '/api/logout'
                token:
                    validation:
                        useBearerToken: false
                        headerName: 'X-Auth-Token'
